server_ip: "192.168.137.240"
msg_port: 8888
data_port: 8889
channels:
  - name: "Ch. 1"
    coords: [1, 1]
    type: 0
    labels:
      left: ["&Delta;I<sub>ds</sub>", "A"]
      bottom: ["Time", "s"]
  - name: "Ch. 2"
    coords: [2, 1]
    type: 0
    labels:
      left: ["&Delta;I<sub>ds</sub>", "A"]
      bottom: ["Time", "s"]
BUF_LEN: 32
sample_rates: [5, 10, 20, 30, 40, 50]
sample_rate: 20
time_ranges: [1, 10, 30, 60]
time_range: 1
timer: 600
max_record_time: 300
bandpass: [[10, 8.0e+3], 2]
notch: [50, 20]
commands:
  start: "Start acquisition"
  stop: "Stop acquisition"
  stream: "Stream (on/off)"
  rec: "Start recording"
  save name: "Save data"
  pause: "Pause recording"
  info: "Get info"
